"""
Second expansion: add 150+ more places to reach 500+ total.
Focus on cities with fewer entries and new cities.
"""
import json
import os

MORE_DATA = [
    # ====== MORE RAJASTHAN ======
    # Jodhpur expansion
    {"name": "Umaid Bhawan Palace", "city": "jodhpur", "state": "Rajasthan", "lat": 26.2749, "lng": 73.0448, "category": "monument", "subcategory": "palace", "rating": 4.7, "description": "Art Deco palace divided between royal residence, museum, and Taj luxury hotel; last grand palace built in India.", "avg_cost": 100, "visit_duration": 2.0, "best_time": "morning", "tags": ["history", "architecture", "culture"], "budget_level": "low"},
    {"name": "Toorji Ka Jhalra", "city": "jodhpur", "state": "Rajasthan", "lat": 26.297, "lng": 73.024, "category": "historic", "subcategory": "stepwell", "rating": 4.3, "description": "Beautifully restored 18th-century stepwell in the old city with intricately carved sandstone walls and cafes nearby.", "avg_cost": 0, "visit_duration": 0.5, "best_time": "afternoon", "tags": ["history", "architecture", "photography"], "budget_level": "free"},
    {"name": "Mandore Gardens", "city": "jodhpur", "state": "Rajasthan", "lat": 26.327, "lng": 73.008, "category": "park", "subcategory": "heritage_garden", "rating": 4.2, "description": "Royal cenotaph gardens with elaborate carved dewals of Jodhpur's rulers and the Hall of Heroes rock shrine.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "morning", "tags": ["history", "nature", "architecture"], "budget_level": "free"},

    # Udaipur expansion
    {"name": "Jag Mandir", "city": "udaipur", "state": "Rajasthan", "lat": 24.569, "lng": 73.683, "category": "monument", "subcategory": "palace", "rating": 4.5, "description": "Island palace on Lake Pichola where Emperor Shah Jahan sought refuge, with Mughal-style gardens and elephant carvings.", "avg_cost": 400, "visit_duration": 2.0, "best_time": "evening", "tags": ["history", "architecture", "photography"], "budget_level": "medium"},
    {"name": "Bagore Ki Haveli", "city": "udaipur", "state": "Rajasthan", "lat": 24.577, "lng": 73.681, "category": "museum", "subcategory": "haveli_museum", "rating": 4.3, "description": "Grand 18th-century haveli with 138 rooms housing costume exhibits plus a mesmerizing evening Dharohar dance show.", "avg_cost": 100, "visit_duration": 2.0, "best_time": "evening", "tags": ["culture", "art", "history"], "budget_level": "low"},
    {"name": "Vintage Car Museum", "city": "udaipur", "state": "Rajasthan", "lat": 24.561, "lng": 73.703, "category": "museum", "subcategory": "automobile", "rating": 4.1, "description": "Royal collection of classic cars including a 1934 Rolls-Royce, 1938 Cadillac, and a solar-powered rickshaw.", "avg_cost": 250, "visit_duration": 1.0, "best_time": "afternoon", "tags": ["culture", "history"], "budget_level": "medium"},

    # ====== MORE KERALA ======
    # Alleppey expansion
    {"name": "Alappuzha Beach", "city": "alleppey", "state": "Kerala", "lat": 9.495, "lng": 76.325, "category": "nature", "subcategory": "beach", "rating": 4.2, "description": "Palm-fringed beach with an old lighthouse, pier stretching into the Arabian Sea, and colourful fishing boats.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "evening", "tags": ["nature", "beaches", "photography"], "budget_level": "free"},
    {"name": "Krishnapuram Palace", "city": "alleppey", "state": "Kerala", "lat": 9.347, "lng": 76.38, "category": "monument", "subcategory": "palace", "rating": 4.0, "description": "18th-century Kerala-style palace with a 49-sq-ft mural of Gajendra Moksham, the largest in Kerala.", "avg_cost": 20, "visit_duration": 1.0, "best_time": "afternoon", "tags": ["history", "art", "culture"], "budget_level": "low"},

    # Kochi expansion
    {"name": "Fort Kochi", "city": "kochi", "state": "Kerala", "lat": 9.965, "lng": 76.241, "category": "interesting_places", "subcategory": "heritage_area", "rating": 4.4, "description": "Historic neighborhood with Portuguese churches, Dutch Palace, Jewish synagogue, and iconic Chinese fishing nets.", "avg_cost": 0, "visit_duration": 3.0, "best_time": "morning", "tags": ["history", "culture", "architecture", "photography"], "budget_level": "free"},
    {"name": "Mattancherry Palace", "city": "kochi", "state": "Kerala", "lat": 9.958, "lng": 76.259, "category": "monument", "subcategory": "palace", "rating": 4.3, "description": "16th-century Dutch Palace with spectacular Kerala murals depicting scenes from the Ramayana and Mahabharata.", "avg_cost": 5, "visit_duration": 1.0, "best_time": "morning", "tags": ["history", "art", "culture"], "budget_level": "low"},

    # Munnar expansion
    {"name": "Eravikulam National Park", "city": "munnar", "state": "Kerala", "lat": 10.177, "lng": 77.062, "category": "nature", "subcategory": "national_park", "rating": 4.5, "description": "Home to the endangered Nilgiri tahr mountain goat, with rolling grasslands and breathtaking shola forest views.", "avg_cost": 125, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Mattupetty Dam", "city": "munnar", "state": "Kerala", "lat": 10.106, "lng": 77.126, "category": "nature", "subcategory": "dam", "rating": 4.1, "description": "Scenic reservoir surrounded by tea gardens and evergreen forests, with boating and views of grazing cattle.", "avg_cost": 50, "visit_duration": 1.5, "best_time": "morning", "tags": ["nature", "photography"], "budget_level": "low"},

    # ====== MORE TAMIL NADU ======
    # Chennai expansion
    {"name": "Kapaleeshwarar Temple", "city": "chennai", "state": "Tamil Nadu", "lat": 13.034, "lng": 80.269, "category": "religious", "subcategory": "temple", "rating": 4.5, "description": "Stunning 7th-century Dravidian temple with a 36m-tall painted gopuram dedicated to Lord Shiva in Mylapore.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["spiritual", "architecture", "history"], "budget_level": "free"},
    {"name": "Marina Beach", "city": "chennai", "state": "Tamil Nadu", "lat": 13.05, "lng": 80.282, "category": "nature", "subcategory": "beach", "rating": 4.2, "description": "India's longest natural urban beach stretching 13 km, a sunrise hotspot with lighthouse and Heritage buildings.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "morning", "tags": ["nature", "beaches", "photography"], "budget_level": "free"},

    # Madurai expansion
    {"name": "Gandhi Memorial Museum", "city": "madurai", "state": "Tamil Nadu", "lat": 9.912, "lng": 78.118, "category": "museum", "subcategory": "memorial", "rating": 4.2, "description": "Museum in a former palace showcasing Mahatma Gandhi's blood-stained dhoti from assassination and freedom struggle exhibits.", "avg_cost": 5, "visit_duration": 1.5, "best_time": "afternoon", "tags": ["history", "culture"], "budget_level": "low"},
    {"name": "Thirumalai Nayakkar Mahal", "city": "madurai", "state": "Tamil Nadu", "lat": 9.917, "lng": 78.121, "category": "monument", "subcategory": "palace", "rating": 4.3, "description": "Grand 17th-century Nayak palace with soaring pillars, stucco dome, and light and sound show.", "avg_cost": 50, "visit_duration": 1.5, "best_time": "evening", "tags": ["history", "architecture", "culture"], "budget_level": "low"},

    # Rameswaram
    {"name": "Ramanathaswamy Temple", "city": "rameswaram", "state": "Tamil Nadu", "lat": 9.2885, "lng": 79.3173, "category": "religious", "subcategory": "temple", "rating": 4.7, "description": "One of the 12 Jyotirlingas with the world's longest temple corridor (1,212m) of ornately carved granite pillars.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "morning", "tags": ["spiritual", "architecture", "history"], "budget_level": "free"},
    {"name": "Pamban Bridge", "city": "rameswaram", "state": "Tamil Nadu", "lat": 9.278, "lng": 79.213, "category": "architecture", "subcategory": "bridge", "rating": 4.4, "description": "India's first sea bridge — a spectacular 2-km railway bridge over the Palk Strait connecting Rameswaram island.", "avg_cost": 0, "visit_duration": 0.5, "best_time": "evening", "tags": ["architecture", "photography", "adventure"], "budget_level": "free"},
    {"name": "Dhanushkodi", "city": "rameswaram", "state": "Tamil Nadu", "lat": 9.175, "lng": 79.429, "category": "nature", "subcategory": "ghost_town", "rating": 4.3, "description": "Haunting ghost town at India's tip destroyed by the 1964 cyclone, where the Bay of Bengal meets the Indian Ocean.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "history", "adventure", "photography"], "budget_level": "free"},
    {"name": "APJ Abdul Kalam Memorial", "city": "rameswaram", "state": "Tamil Nadu", "lat": 9.289, "lng": 79.318, "category": "museum", "subcategory": "memorial", "rating": 4.3, "description": "Glass-domed memorial museum dedicated to India's beloved Missile Man President with interactive exhibits.", "avg_cost": 20, "visit_duration": 1.0, "best_time": "afternoon", "tags": ["history", "culture"], "budget_level": "low"},

    # Kodaikanal
    {"name": "Kodaikanal Lake", "city": "kodaikanal", "state": "Tamil Nadu", "lat": 10.236, "lng": 77.489, "category": "nature", "subcategory": "lake", "rating": 4.5, "description": "Star-shaped artificial lake surrounded by dense Shola forests, with pedal boating, cycling, and horse riding.", "avg_cost": 50, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Coaker's Walk", "city": "kodaikanal", "state": "Tamil Nadu", "lat": 10.232, "lng": 77.489, "category": "nature", "subcategory": "viewpoint", "rating": 4.3, "description": "Paved 1-km footpath along steep mountain slopes offering panoramic views of the plains 7,000 feet below.", "avg_cost": 10, "visit_duration": 1.0, "best_time": "morning", "tags": ["nature", "photography"], "budget_level": "low"},
    {"name": "Pillar Rocks", "city": "kodaikanal", "state": "Tamil Nadu", "lat": 10.224, "lng": 77.478, "category": "nature", "subcategory": "geological", "rating": 4.2, "description": "Three massive granite pillars rising 120m from a deep forested gorge, often shrouded in magical mist.", "avg_cost": 10, "visit_duration": 1.0, "best_time": "morning", "tags": ["nature", "photography"], "budget_level": "low"},
    {"name": "Bryant Park", "city": "kodaikanal", "state": "Tamil Nadu", "lat": 10.237, "lng": 77.494, "category": "park", "subcategory": "botanical_garden", "rating": 4.1, "description": "Landscaped botanical garden on the lake shore with 325 species of hybrid roses and annual flower shows.", "avg_cost": 30, "visit_duration": 1.0, "best_time": "morning", "tags": ["nature", "photography"], "budget_level": "low"},
    {"name": "Bear Shola Falls", "city": "kodaikanal", "state": "Tamil Nadu", "lat": 10.246, "lng": 77.485, "category": "nature", "subcategory": "waterfall", "rating": 4.0, "description": "Secluded seasonal waterfall named after bears once spotted drinking here, surrounded by dense canopy.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["nature", "adventure"], "budget_level": "free"},

    # ====== MORE KARNATAKA ======
    # Mysore expansion
    {"name": "Chamundi Hill Temple", "city": "mysore", "state": "Karnataka", "lat": 12.273, "lng": 76.67, "category": "religious", "subcategory": "temple", "rating": 4.4, "description": "Hilltop temple of goddess Chamundeshwari with a giant Nandi statue halfway up the 1,000 steps.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "morning", "tags": ["spiritual", "nature", "photography"], "budget_level": "free"},
    {"name": "Brindavan Gardens", "city": "mysore", "state": "Karnataka", "lat": 12.421, "lng": 76.573, "category": "park", "subcategory": "terraced_garden", "rating": 4.3, "description": "Beautifully terraced Mughal gardens below the KRS Dam, with musical dancing fountain show in the evening.", "avg_cost": 25, "visit_duration": 2.0, "best_time": "evening", "tags": ["nature", "photography", "culture"], "budget_level": "low"},
    {"name": "Mysore Zoo", "city": "mysore", "state": "Karnataka", "lat": 12.301, "lng": 76.663, "category": "nature", "subcategory": "zoo", "rating": 4.2, "description": "One of India's oldest and best-maintained zoos (est. 1892) with elephants, giraffes, and white tigers.", "avg_cost": 60, "visit_duration": 2.5, "best_time": "morning", "tags": ["nature", "adventure"], "budget_level": "low"},

    # ====== HIMACHAL PRADESH ======
    # Shimla expansion
    {"name": "The Ridge", "city": "shimla", "state": "Himachal Pradesh", "lat": 31.105, "lng": 77.171, "category": "interesting_places", "subcategory": "promenade", "rating": 4.3, "description": "Shimla's iconic open promenade with panoramic mountain views, colonial architecture, and the Christ Church.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "evening", "tags": ["nature", "photography", "culture"], "budget_level": "free"},
    {"name": "Jakhu Temple", "city": "shimla", "state": "Himachal Pradesh", "lat": 31.109, "lng": 77.186, "category": "religious", "subcategory": "temple", "rating": 4.2, "description": "Ancient Hanuman temple atop the highest peak in Shimla with a 108-ft Hanuman statue and monkey colonies.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "morning", "tags": ["spiritual", "nature", "adventure"], "budget_level": "free"},
    {"name": "Kufri", "city": "shimla", "state": "Himachal Pradesh", "lat": 31.098, "lng": 77.267, "category": "nature", "subcategory": "hill_station", "rating": 4.1, "description": "Popular hill station near Shimla for horse riding, skiing in winter, and nature walks through cedar forests.", "avg_cost": 200, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},

    # Manali expansion
    {"name": "Rohtang Pass", "city": "manali", "state": "Himachal Pradesh", "lat": 32.372, "lng": 77.248, "category": "nature", "subcategory": "mountain_pass", "rating": 4.5, "description": "Iconic 13,054 ft Himalayan pass with snow activities, panoramic views, and gateway to Lahaul-Spiti valley.", "avg_cost": 500, "visit_duration": 4.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "medium"},
    {"name": "Solang Valley", "city": "manali", "state": "Himachal Pradesh", "lat": 32.324, "lng": 77.157, "category": "nature", "subcategory": "valley", "rating": 4.4, "description": "Adventure sports paradise with paragliding, zorbing, skiing, and ropeway rides set against snow-capped peaks.", "avg_cost": 800, "visit_duration": 4.0, "best_time": "morning", "tags": ["nature", "adventure", "sports"], "budget_level": "medium"},
    {"name": "Old Manali", "city": "manali", "state": "Himachal Pradesh", "lat": 32.252, "lng": 77.184, "category": "interesting_places", "subcategory": "village", "rating": 4.2, "description": "Bohemian village across the Manalsu stream with charming cafes, bakeries, and hippie culture.", "avg_cost": 200, "visit_duration": 2.0, "best_time": "afternoon", "tags": ["food", "culture", "nature"], "budget_level": "low"},

    # Dharamshala
    {"name": "Dalai Lama Temple Complex", "city": "dharamshala", "state": "Himachal Pradesh", "lat": 32.238, "lng": 76.323, "category": "religious", "subcategory": "monastery", "rating": 4.7, "description": "Official residence of the 14th Dalai Lama and spiritual centre of Tibetan Buddhism in exile.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "morning", "tags": ["spiritual", "culture", "history"], "budget_level": "free"},
    {"name": "Bhagsu Waterfall", "city": "dharamshala", "state": "Himachal Pradesh", "lat": 32.247, "lng": 76.334, "category": "nature", "subcategory": "waterfall", "rating": 4.1, "description": "Popular waterfall near Bhagsunath Temple, a favourite among backpackers with a cafe perched at the top.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "morning", "tags": ["nature", "adventure"], "budget_level": "free"},
    {"name": "Triund Trek", "city": "dharamshala", "state": "Himachal Pradesh", "lat": 32.254, "lng": 76.341, "category": "nature", "subcategory": "trek", "rating": 4.6, "description": "Moderate 9-km trek to a stunning alpine meadow at 2,850m with 360-degree Dhauladhar range and valley views.", "avg_cost": 200, "visit_duration": 8.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Norbulingka Institute", "city": "dharamshala", "state": "Himachal Pradesh", "lat": 32.173, "lng": 76.274, "category": "museum", "subcategory": "cultural_centre", "rating": 4.3, "description": "Centre preserving Tibetan culture with traditional arts, wood-carving workshops, and a Japanese-style garden.", "avg_cost": 50, "visit_duration": 2.0, "best_time": "afternoon", "tags": ["culture", "art", "nature"], "budget_level": "low"},
    {"name": "HPCA Cricket Stadium", "city": "dharamshala", "state": "Himachal Pradesh", "lat": 32.225, "lng": 76.323, "category": "interesting_places", "subcategory": "stadium", "rating": 4.4, "description": "World's most picturesque cricket ground at 1,457m elevation with snow-clad Dhauladhar peaks as backdrop.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "afternoon", "tags": ["sports", "photography"], "budget_level": "free"},

    # ====== MORE UTTARAKHAND ======
    # Rishikesh expansion
    {"name": "Triveni Ghat", "city": "rishikesh", "state": "Uttarakhand", "lat": 30.108, "lng": 78.297, "category": "religious", "subcategory": "ghat", "rating": 4.3, "description": "Sacred confluence of Ganga, Yamuna, and Saraswati rivers with mesmerizing evening Ganga Aarti ceremony.", "avg_cost": 0, "visit_duration": 1.5, "best_time": "evening", "tags": ["spiritual", "culture"], "budget_level": "free"},
    {"name": "Neelkanth Mahadev Temple", "city": "rishikesh", "state": "Uttarakhand", "lat": 30.13, "lng": 78.397, "category": "religious", "subcategory": "temple", "rating": 4.4, "description": "Hilltop Shiva temple deep in the forest where Shiva drank the poison that turned his throat blue.", "avg_cost": 0, "visit_duration": 3.0, "best_time": "morning", "tags": ["spiritual", "adventure", "nature"], "budget_level": "free"},

    # Nainital expansion
    {"name": "Snow View Point", "city": "nainital", "state": "Uttarakhand", "lat": 29.399, "lng": 79.465, "category": "nature", "subcategory": "viewpoint", "rating": 4.3, "description": "Ropeway-accessible viewpoint at 2,270m offering stunning views of Nanda Devi, Trishul, and other Himalayan peaks.", "avg_cost": 200, "visit_duration": 1.5, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Eco Cave Gardens", "city": "nainital", "state": "Uttarakhand", "lat": 29.388, "lng": 79.455, "category": "nature", "subcategory": "cave", "rating": 4.0, "description": "Interconnected natural rock caves named after animals with a musical fountain and hanging garden.", "avg_cost": 35, "visit_duration": 1.0, "best_time": "afternoon", "tags": ["nature", "adventure"], "budget_level": "low"},
    {"name": "Tiffin Top", "city": "nainital", "state": "Uttarakhand", "lat": 29.378, "lng": 79.452, "category": "nature", "subcategory": "hill", "rating": 4.2, "description": "Hilltop viewpoint reached via pony ride through oak forests, offering panoramic views of Nainital and beyond.", "avg_cost": 300, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},

    # ====== GUJARAT ======
    # Ahmedabad expansion
    {"name": "Sabarmati Ashram", "city": "ahmedabad", "state": "Gujarat", "lat": 23.0608, "lng": 72.5805, "category": "historic", "subcategory": "ashram", "rating": 4.6, "description": "Mahatma Gandhi's home for 12 years and launchpad of the Dandi Salt March, with museum and spinning wheel.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "morning", "tags": ["history", "culture", "spiritual"], "budget_level": "free"},
    {"name": "Adalaj Stepwell", "city": "ahmedabad", "state": "Gujarat", "lat": 23.164, "lng": 72.577, "category": "monument", "subcategory": "stepwell", "rating": 4.5, "description": "Intricately carved five-story stepwell from 1499 with Hindu, Islamic, and Jain motifs, naturally cool inside.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["history", "architecture", "photography"], "budget_level": "free"},
    {"name": "Sidi Saiyyed Mosque", "city": "ahmedabad", "state": "Gujarat", "lat": 23.024, "lng": 72.572, "category": "monument", "subcategory": "mosque", "rating": 4.3, "description": "Famous for its exquisite stone lattice window (jali) depicting an intricate tree-of-life, icon of Ahmedabad.", "avg_cost": 0, "visit_duration": 0.5, "best_time": "morning", "tags": ["history", "architecture", "art"], "budget_level": "free"},

    # Somnath/Junagadh
    {"name": "Somnath Temple", "city": "somnath", "state": "Gujarat", "lat": 20.888, "lng": 70.401, "category": "religious", "subcategory": "temple", "rating": 4.7, "description": "One of the 12 sacred Jyotirlingas at the Arabian Sea shore, rebuilt multiple times, with spectacular light show.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "evening", "tags": ["spiritual", "history", "architecture"], "budget_level": "free"},
    {"name": "Gir National Park", "city": "somnath", "state": "Gujarat", "lat": 21.124, "lng": 70.79, "category": "nature", "subcategory": "national_park", "rating": 4.6, "description": "Only habitat of the Asiatic lion in the wild; 1,412 sq km sanctuary with jeep safari spotting 700+ lions.", "avg_cost": 1500, "visit_duration": 4.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "medium"},

    # ====== ANDHRA PRADESH ======
    # Tirupati
    {"name": "Tirumala Venkateswara Temple", "city": "tirupati", "state": "Andhra Pradesh", "lat": 13.683, "lng": 79.347, "category": "religious", "subcategory": "temple", "rating": 4.8, "description": "World's richest and most visited Hindu temple atop the Seven Hills, attracting 50,000+ pilgrims daily.", "avg_cost": 0, "visit_duration": 4.0, "best_time": "morning", "tags": ["spiritual", "culture"], "budget_level": "free"},
    {"name": "Sri Venkateswara National Park", "city": "tirupati", "state": "Andhra Pradesh", "lat": 13.65, "lng": 79.35, "category": "nature", "subcategory": "national_park", "rating": 4.2, "description": "Biodiverse Eastern Ghats sanctuary with orchids, waterfalls, and trekking trails through dense deciduous forests.", "avg_cost": 50, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Talakona Waterfall", "city": "tirupati", "state": "Andhra Pradesh", "lat": 13.675, "lng": 79.263, "category": "nature", "subcategory": "waterfall", "rating": 4.3, "description": "Andhra Pradesh's highest waterfall at 270 feet, a trekking and nature lover's paradise inside the national park.", "avg_cost": 50, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Chandragiri Fort", "city": "tirupati", "state": "Andhra Pradesh", "lat": 13.584, "lng": 79.318, "category": "monument", "subcategory": "fort", "rating": 4.1, "description": "11th-century fort where the British East India Company received the land grant for Madras (Chennai).", "avg_cost": 25, "visit_duration": 1.5, "best_time": "morning", "tags": ["history", "architecture"], "budget_level": "low"},

    # Visakhapatnam
    {"name": "Araku Valley", "city": "visakhapatnam", "state": "Andhra Pradesh", "lat": 18.327, "lng": 82.876, "category": "nature", "subcategory": "valley", "rating": 4.5, "description": "Hill station at 1,300m in Eastern Ghats with coffee plantations, tribal museum, and scenic train journey.", "avg_cost": 200, "visit_duration": 6.0, "best_time": "morning", "tags": ["nature", "adventure", "culture", "photography"], "budget_level": "low"},
    {"name": "Borra Caves", "city": "visakhapatnam", "state": "Andhra Pradesh", "lat": 18.28, "lng": 83.036, "category": "nature", "subcategory": "cave", "rating": 4.3, "description": "Million-year-old limestone caves at 1,400m with spectacular stalactite and stalagmite formations.", "avg_cost": 40, "visit_duration": 1.5, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Kailasagiri", "city": "visakhapatnam", "state": "Andhra Pradesh", "lat": 17.756, "lng": 83.373, "category": "park", "subcategory": "hilltop_park", "rating": 4.2, "description": "Hilltop park with giant Shiva-Parvati statues, ropeway ride over the Bay of Bengal, and panoramic views.", "avg_cost": 100, "visit_duration": 2.0, "best_time": "evening", "tags": ["nature", "photography", "adventure"], "budget_level": "low"},
    {"name": "Submarine Museum", "city": "visakhapatnam", "state": "Andhra Pradesh", "lat": 17.71, "lng": 83.328, "category": "museum", "subcategory": "military", "rating": 4.1, "description": "Decommissioned INS Kurusura submarine converted into a unique walk-through military museum on the beach.", "avg_cost": 40, "visit_duration": 1.0, "best_time": "afternoon", "tags": ["history", "adventure"], "budget_level": "low"},

    # ====== JAMMU & KASHMIR ======
    # Srinagar
    {"name": "Dal Lake", "city": "srinagar", "state": "Jammu & Kashmir", "lat": 34.119, "lng": 74.867, "category": "nature", "subcategory": "lake", "rating": 4.7, "description": "Iconic Kashmiri lake with ornate houseboats, floating vegetable markets, and mesmerizing Shikara rides.", "avg_cost": 500, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "photography", "culture", "adventure"], "budget_level": "medium"},
    {"name": "Mughal Gardens (Nishat Bagh)", "city": "srinagar", "state": "Jammu & Kashmir", "lat": 34.113, "lng": 74.886, "category": "park", "subcategory": "terraced_garden", "rating": 4.5, "description": "Garden of Joy — largest Mughal garden in Kashmir with 12 terraces symbolizing zodiac signs, overlooking Dal Lake.", "avg_cost": 30, "visit_duration": 1.5, "best_time": "morning", "tags": ["nature", "architecture", "photography"], "budget_level": "low"},
    {"name": "Shalimar Bagh", "city": "srinagar", "state": "Jammu & Kashmir", "lat": 34.149, "lng": 74.874, "category": "park", "subcategory": "mughal_garden", "rating": 4.4, "description": "Crown of Srinagar — Emperor Jahangir's garden of love with cascading fountains and chinars over Dal Lake.", "avg_cost": 30, "visit_duration": 1.5, "best_time": "afternoon", "tags": ["nature", "history", "photography"], "budget_level": "low"},
    {"name": "Hazratbal Shrine", "city": "srinagar", "state": "Jammu & Kashmir", "lat": 34.131, "lng": 74.84, "category": "religious", "subcategory": "mosque", "rating": 4.4, "description": "White marble mosque housing a relic believed to be a hair of Prophet Muhammad, set beautifully on Dal Lake.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["spiritual", "architecture", "photography"], "budget_level": "free"},
    {"name": "Pari Mahal", "city": "srinagar", "state": "Jammu & Kashmir", "lat": 34.079, "lng": 74.868, "category": "monument", "subcategory": "ruins", "rating": 4.2, "description": "Mughal-era terraced garden ruin known as the 'Palace of Fairies', perched above Srinagar with magical night illumination.", "avg_cost": 20, "visit_duration": 1.0, "best_time": "evening", "tags": ["history", "photography", "nature"], "budget_level": "low"},

    # Leh-Ladakh
    {"name": "Pangong Tso Lake", "city": "leh", "state": "Ladakh", "lat": 33.759, "lng": 78.663, "category": "nature", "subcategory": "lake", "rating": 4.8, "description": "Stunning high-altitude lake at 14,270 ft stretching from India to China, changing colours from blue to green.", "avg_cost": 0, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "photography", "adventure"], "budget_level": "free"},
    {"name": "Nubra Valley", "city": "leh", "state": "Ladakh", "lat": 34.598, "lng": 77.588, "category": "nature", "subcategory": "valley", "rating": 4.6, "description": "Cold desert valley beyond Khardung La with sand dunes, double-humped Bactrian camels, and ancient monasteries.", "avg_cost": 500, "visit_duration": 6.0, "best_time": "morning", "tags": ["nature", "adventure", "culture", "photography"], "budget_level": "medium"},
    {"name": "Thiksey Monastery", "city": "leh", "state": "Ladakh", "lat": 34.055, "lng": 77.667, "category": "religious", "subcategory": "monastery", "rating": 4.6, "description": "12-story monastery resembling Lhasa's Potala Palace with a 15m-tall Maitreya Buddha and stunning valley views.", "avg_cost": 50, "visit_duration": 2.0, "best_time": "morning", "tags": ["spiritual", "architecture", "photography", "culture"], "budget_level": "low"},
    {"name": "Magnetic Hill", "city": "leh", "state": "Ladakh", "lat": 34.269, "lng": 77.229, "category": "interesting_places", "subcategory": "natural_wonder", "rating": 4.0, "description": "Gravity-defying hill where vehicles appear to roll uphill due to an optical illusion created by the surrounding terrain.", "avg_cost": 0, "visit_duration": 0.5, "best_time": "afternoon", "tags": ["adventure", "nature"], "budget_level": "free"},
    {"name": "Shanti Stupa", "city": "leh", "state": "Ladakh", "lat": 34.164, "lng": 77.575, "category": "religious", "subcategory": "stupa", "rating": 4.4, "description": "Japanese-built white-domed peace stupa on a hilltop offering spectacular sunset views over Leh town.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "evening", "tags": ["spiritual", "photography", "nature"], "budget_level": "free"},
    {"name": "Hemis Monastery", "city": "leh", "state": "Ladakh", "lat": 33.917, "lng": 77.702, "category": "religious", "subcategory": "monastery", "rating": 4.5, "description": "Largest and wealthiest monastery in Ladakh, famous for its annual masked dance festival and treasured thangkas.", "avg_cost": 50, "visit_duration": 2.0, "best_time": "morning", "tags": ["spiritual", "culture", "art"], "budget_level": "low"},

    # ====== MORE GOA ======
    {"name": "Basilica of Bom Jesus", "city": "goa", "state": "Goa", "lat": 15.501, "lng": 73.912, "category": "religious", "subcategory": "church", "rating": 4.6, "description": "UNESCO World Heritage baroque church housing the mortal remains of St. Francis Xavier in a silver casket.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["spiritual", "architecture", "history"], "budget_level": "free"},
    {"name": "Calangute Beach", "city": "goa", "state": "Goa", "lat": 15.544, "lng": 73.755, "category": "nature", "subcategory": "beach", "rating": 4.1, "description": "Goa's largest and most popular beach with water sports, beach shacks, flea markets, and vibrant nightlife.", "avg_cost": 500, "visit_duration": 3.0, "best_time": "evening", "tags": ["nature", "beaches", "adventure", "food"], "budget_level": "medium"},
    {"name": "Old Goa Churches", "city": "goa", "state": "Goa", "lat": 15.504, "lng": 73.91, "category": "historic", "subcategory": "church_complex", "rating": 4.4, "description": "Cluster of UNESCO-listed 16th-17th century Portuguese churches including the grand Se Cathedral and St. Cajetan.", "avg_cost": 0, "visit_duration": 2.0, "best_time": "morning", "tags": ["history", "architecture", "spiritual"], "budget_level": "free"},
    {"name": "Spice Plantations", "city": "goa", "state": "Goa", "lat": 15.44, "lng": 74.02, "category": "nature", "subcategory": "plantation", "rating": 4.2, "description": "Guided tours through aromatic spice estates with lunch buffet, elephant bathing, and Ayurvedic spa options.", "avg_cost": 400, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "food", "culture"], "budget_level": "medium"},

    # ====== PUNJAB ======
    # Amritsar expansion
    {"name": "Partition Museum", "city": "amritsar", "state": "Punjab", "lat": 31.621, "lng": 74.876, "category": "museum", "subcategory": "historical", "rating": 4.5, "description": "Deeply moving museum documenting the 1947 Partition through personal stories, photographs, and artifacts.", "avg_cost": 50, "visit_duration": 2.0, "best_time": "afternoon", "tags": ["history", "culture"], "budget_level": "low"},
    {"name": "Gobindgarh Fort", "city": "amritsar", "state": "Punjab", "lat": 31.627, "lng": 74.871, "category": "monument", "subcategory": "fort", "rating": 4.2, "description": "Restored 18th-century fortress with live war re-enactments, 7D theatre, and Sikh heritage museum.", "avg_cost": 200, "visit_duration": 2.5, "best_time": "afternoon", "tags": ["history", "adventure", "culture"], "budget_level": "low"},

    # ====== CHHATTISGARH ======
    {"name": "Chitrakote Falls", "city": "jagdalpur", "state": "Chhattisgarh", "lat": 19.204, "lng": 81.701, "category": "nature", "subcategory": "waterfall", "rating": 4.5, "description": "India's broadest waterfall known as the 'Niagara of India', a horseshoe-shaped cascade on the Indravati River.", "avg_cost": 20, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "photography", "adventure"], "budget_level": "low"},
    {"name": "Tirathgarh Falls", "city": "jagdalpur", "state": "Chhattisgarh", "lat": 18.927, "lng": 81.792, "category": "nature", "subcategory": "waterfall", "rating": 4.3, "description": "Multi-tiered milky waterfall cascading down 300 feet through dense sal forest inside Kanger Valley National Park.", "avg_cost": 20, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "photography", "adventure"], "budget_level": "low"},
    {"name": "Kanger Valley National Park", "city": "jagdalpur", "state": "Chhattisgarh", "lat": 18.927, "lng": 81.9, "category": "nature", "subcategory": "national_park", "rating": 4.4, "description": "Biosphere reserve with limestone caves, underground streams, subterranean fish, and endemic Bastar hill myna.", "avg_cost": 50, "visit_duration": 4.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},

    # ====== JHARKHAND ======
    {"name": "Hundru Falls", "city": "ranchi", "state": "Jharkhand", "lat": 23.439, "lng": 85.499, "category": "nature", "subcategory": "waterfall", "rating": 4.2, "description": "Jharkhand's highest waterfall plunging 98 metres down rocky terrain on the Subarnarekha River.", "avg_cost": 25, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "low"},
    {"name": "Jonha Falls", "city": "ranchi", "state": "Jharkhand", "lat": 23.358, "lng": 85.507, "category": "nature", "subcategory": "waterfall", "rating": 4.1, "description": "Picturesque 43m waterfall with 722 steps leading to the base, surrounded by dense forests and a Buddhist shrine.", "avg_cost": 10, "visit_duration": 2.0, "best_time": "morning", "tags": ["nature", "adventure", "spiritual"], "budget_level": "low"},
    {"name": "Patratu Valley", "city": "ranchi", "state": "Jharkhand", "lat": 23.671, "lng": 85.318, "category": "nature", "subcategory": "valley", "rating": 4.0, "description": "Scenic valley with serpentine mountain roads, reservoir, and lush green hills — Jharkhand's hidden gem.", "avg_cost": 0, "visit_duration": 3.0, "best_time": "morning", "tags": ["nature", "adventure", "photography"], "budget_level": "free"},

    # ====== WEST BENGAL ======
    # Darjeeling expansion
    {"name": "Batasia Loop", "city": "darjeeling", "state": "West Bengal", "lat": 27.04, "lng": 88.259, "category": "interesting_places", "subcategory": "railway", "rating": 4.3, "description": "Spectacular spiral railway loop of the toy train with a war memorial garden and panoramic Kanchenjunga views.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["photography", "nature", "culture"], "budget_level": "free"},
    {"name": "Peace Pagoda Darjeeling", "city": "darjeeling", "state": "West Bengal", "lat": 27.025, "lng": 88.245, "category": "religious", "subcategory": "stupa", "rating": 4.2, "description": "Japanese-built white peace pagoda with four golden Buddha avatars, offering serene views of the tea gardens.", "avg_cost": 0, "visit_duration": 1.0, "best_time": "morning", "tags": ["spiritual", "photography", "nature"], "budget_level": "free"},
    {"name": "Happy Valley Tea Estate", "city": "darjeeling", "state": "West Bengal", "lat": 27.037, "lng": 88.257, "category": "interesting_places", "subcategory": "plantation", "rating": 4.3, "description": "One of Darjeeling's oldest tea gardens (1854) offering guided tours of tea processing and tastings.", "avg_cost": 100, "visit_duration": 1.5, "best_time": "morning", "tags": ["culture", "nature", "food"], "budget_level": "low"},

    # ====== MADHYA PRADESH ======
    # Bhopal expansion
    {"name": "Upper Lake", "city": "bhopal", "state": "Madhya Pradesh", "lat": 23.249, "lng": 77.38, "category": "nature", "subcategory": "lake", "rating": 4.2, "description": "One of the largest artificial lakes in Asia, offering boat rides, water sports, and serene sunset views.", "avg_cost": 50, "visit_duration": 1.5, "best_time": "evening", "tags": ["nature", "photography", "adventure"], "budget_level": "low"},
    {"name": "Bhimbetka Rock Shelters", "city": "bhopal", "state": "Madhya Pradesh", "lat": 22.936, "lng": 77.609, "category": "historic", "subcategory": "archaeological", "rating": 4.6, "description": "UNESCO site with 30,000-year-old prehistoric cave paintings — the oldest known rock art in the Indian subcontinent.", "avg_cost": 25, "visit_duration": 2.0, "best_time": "morning", "tags": ["history", "art", "culture", "photography"], "budget_level": "low"},
    {"name": "Tribal Museum Bhopal", "city": "bhopal", "state": "Madhya Pradesh", "lat": 23.23, "lng": 77.42, "category": "museum", "subcategory": "tribal", "rating": 4.3, "description": "Award-winning museum showcasing Madhya Pradesh tribal art and culture with life-size installations and Gond paintings.", "avg_cost": 10, "visit_duration": 1.5, "best_time": "afternoon", "tags": ["culture", "art", "history"], "budget_level": "low"},

    # ====== TELANGANA ======
    # Hyderabad expansion
    {"name": "Golconda Fort", "city": "hyderabad", "state": "Telangana", "lat": 17.383, "lng": 78.401, "category": "monument", "subcategory": "fort", "rating": 4.5, "description": "Magnificent ruined 13th-century fort famous for its acoustic engineering — a hand clap at the entrance gate is heard 1 km away.", "avg_cost": 25, "visit_duration": 2.5, "best_time": "morning", "tags": ["history", "architecture", "adventure"], "budget_level": "low"},
    {"name": "Qutb Shahi Tombs", "city": "hyderabad", "state": "Telangana", "lat": 17.395, "lng": 78.394, "category": "monument", "subcategory": "tomb", "rating": 4.3, "description": "Peaceful necropolis of the Golconda sultans with 30+ exquisite domed tombs and gardens near Golconda Fort.", "avg_cost": 25, "visit_duration": 1.5, "best_time": "morning", "tags": ["history", "architecture", "photography"], "budget_level": "low"},

    # ====== AGRA ======
    {"name": "Fatehpur Sikri", "city": "agra", "state": "Uttar Pradesh", "lat": 27.0945, "lng": 77.661, "category": "monument", "subcategory": "mughal_city", "rating": 4.6, "description": "UNESCO ghost city built by Akbar in 1571, abandoned after 14 years, with pristine Buland Darwaza and Panch Mahal.", "avg_cost": 50, "visit_duration": 3.0, "best_time": "morning", "tags": ["history", "architecture", "culture"], "budget_level": "low"},
    {"name": "Itmad-ud-Daulah", "city": "agra", "state": "Uttar Pradesh", "lat": 27.193, "lng": 78.031, "category": "monument", "subcategory": "tomb", "rating": 4.4, "description": "Exquisite marble tomb known as the 'Baby Taj', regarded as the draft for the Taj Mahal with finest pietra dura inlay.", "avg_cost": 25, "visit_duration": 1.0, "best_time": "morning", "tags": ["history", "architecture", "photography"], "budget_level": "low"},
    {"name": "Mehtab Bagh", "city": "agra", "state": "Uttar Pradesh", "lat": 27.177, "lng": 78.039, "category": "park", "subcategory": "mughal_garden", "rating": 4.3, "description": "Moonlight Garden across the Yamuna offering perfect Taj Mahal views from the river bank, ideal at sunset.", "avg_cost": 50, "visit_duration": 1.0, "best_time": "evening", "tags": ["photography", "nature", "architecture"], "budget_level": "low"},
]

def main():
    import os
    dataset_path = os.path.join(os.path.dirname(__file__), 'data', 'places_dataset.json')
    
    with open(dataset_path, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    existing_names = {(p['name'].lower(), p['city'].lower()) for p in existing}
    
    added = 0
    skipped = 0
    for place in MORE_DATA:
        key = (place['name'].lower(), place['city'].lower())
        if key not in existing_names:
            existing.append(place)
            existing_names.add(key)
            added += 1
        else:
            skipped += 1
    
    with open(dataset_path, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    cities = set(p['city'] for p in existing)
    print(f"Added {added} new places (skipped {skipped} duplicates)")
    print(f"Total: {len(existing)} places across {len(cities)} cities")
    print(f"Cities: {sorted(cities)}")

if __name__ == '__main__':
    main()
